name: release_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  github: ^9.20.0
  http: ^1.1.2
  jinja: ^0.5.0
  path: ^1.9.0
  pubspec_parse: ^1.2.3

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
